# Generated by Django 5.0.3 on 2024-06-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
